<?php $page_title = "PREVIEW Labor Estimator";?>
<?php include("header.php"); ?>
<?php confirm_logged_in(); ?>

		<link rel="stylesheet" href="includes/css/est-styles.css">
		
			<div class="row">

				<div class="row col-lg-12">
					<div id="mainColumn"> <!--main section-->
						<div>
						
							<form action="Submit.html" method="post" enctype="multipart/form-data">
								<div class="form-group">
									<table class="table table-bordered table-condensed">
										<tr><!--Work order info-->
											<th><label form="WorkOrderStart"><span class="FieldInfo">Work Order#:</span></label></th><!--Autogenerated by database-->
											<th><label form="WorkOrderStart"><span class="FieldInfo">Date:</span></label></th>
											
									
										</tr>
										<tr>
											<td><input class="form-control" type="text" name="woNumb" id="woNumb" placeholder="Work Order # will be generated" data-toggle="tooltip" data-placement="top" title="This will be auto generated, or selectable from DB"></td>
											<td><input class="form-control" type="text" name="woDate" id="woDate" placeholder="Date will be generated" data-toggle="tooltip" data-placement="top" title="This will be auto generated, but editable."></td>
											
										</tr><!-- End Work order info -->
									</table>
									<table class="table table-bordered table-condensed">
										<tr>
											<th><label form="WorkOrderStart"><span class="FieldInfo">Client Name:</span></label></th>
											
										</tr>
										<tr>
											<td><input class="form-control" type="text" name="clientName" id="clientName" placeholder="Client Name" data-toggle="tooltip" data-placement="top" title="This will be selectable from DB"></td>
											
										</tr>
									</table>
									<table class="table table-bordered table-condensed">
										<tr>
											<th><label form="WorkOrderStart"><span class="FieldInfo">Project Name:</span></label></th>
											<th><label form="WorkOrderStart"><span class="FieldInfo">Phase Name:</span></label></th>
										</tr>
										<tr>
											<td><input class="form-control" type="text" name="projectName" id="projectName" placeholder="Project Name" data-toggle="tooltip" data-placement="top" title="This will be selectable from DB, or created with this form"></td>
											<td><input class="form-control" type="text" name="projectPhase" id="projectPhase" placeholder="Project Phase" data-toggle="tooltip" data-placement="top" title="This will be electable from DB, or created with this form. This is an optional field."></td>
										</tr>
									</table>
								</div>
								<div class="form-group">
									<table class="table table-bordered table-condensed">Tasks/Scope of work
										<tr>
											<th>Task Number</th>
											<th>Task Name</th>
											<th>O</th>
											<th>M</th>
											<th>P</th>
											<th>Add Row</th>
										</tr>
										<tr>
											<td width="5%"><input class="form-control" type="text" placeholder="#" data-toggle="tooltip" data-placement="top" title="Auto-increment"></td>
											<td width="50%"><input class="form-control" type="text" placeholder="Task Name" data-toggle="tooltip" data-placement="top" title="Free form"></td>
											<td width="5%"><input class="form-control" type="text" placeholder="#" data-toggle="tooltip" data-placement="top" title="Optimistic"></td>
											<td width="5%"><input class="form-control" type="text" placeholder="#" data-toggle="tooltip" data-placement="top" title="Most Likely"></td>
											<td width="5%"><input class="form-control" type="text" placeholder="#" data-toggle="tooltip" data-placement="top" title="Pessemistic"></td>
											<td width="5%"><input class="btn btn-success btn-sm" type="button" name="addRow" value="+" data-toggle="tooltip" data-placement="top" title="Will add more rows, not currently enabled"></td>
										</tr>
									</table>
									<table class="table table-bordered table-condensed">Total labor + PM
										<tr>
											<th>Total hours</th>
											<th>Hours Multiplier</th>
											<th>Total Amount</th>
										</tr>
										<tr>
											<td><input class="form-control" type="text" name="totalHours" id="totalHours" placeholder="(O+M*4+P)/6" data-toggle="tooltip" data-placement="top" title="Total number of hours to quote"></td>
											<td><input class="form-control" type="text" name="perHour" id="perHour" placeholder="$ per hour" data-toggle="tooltip" data-placement="top" title="Autofill based on client, manual entry allowed"></td>
											<td><input class="form-control" type="text" name="totalLabor" id="totalLabor" placeholder="=hours*LaborRate" data-toggle="tooltip" data-placement="top" title="Multiplier"></td>
										</tr>
										<tr>
											<th>PM Time</th>
											<th>PM Rate</th>
											<th>Total PM Amount</th>
										</tr>
										<tr>
											<td><input type="radio" name="pmHours" id="pmHours">20%</td>
											<td><input class="form-control" type="text" name="pmRate" id="pmRate" placeholder="$ per hour"></td>
											<td><input class="form-control" type="text" name="totalLabor" id="totalLabor" placeholder="=(LaborHours*PM%)*PM Rate"></td>
										</tr>
										<tr>
											<td><input type="radio" name="pmHours" id="pmHours">25%</td>
											<!-- <td><input type="radio" name="feeType"id="feeType" data-toggle="tooltip" data-placement="top" title="If selected, the hours, and hour rates will not be visible; just the total">Flat Fee</td>
											<td><input type="radio" name="feeType"id="feeType" data-toggle="tooltip" data-placement="top" title="If selected, the hours, and hour rates will be visible as well as the total">Per Hour</td> -->
										</tr>
										<tr>
											<td><input type="radio" name="pmHours" id="pmHours">30%</td>
										</tr>
									</table>
									<table class="table table-bordered table-condensed">Items to purchase
										<tr>
											<th>Item Number</th>
											<th>Item Description</th>
											<th>Link/File</th>
											<th>Quantity</th>
											<th>Price Per (nmu)</th>
											<th></th>
										</tr>
										<tr>
											<td width="5%"><input class="form-control" type="text" placeholder="#" data-toggle="tooltip" data-placement="top" title="Auto-increment"></td>
											<td><input class="form-control" type="text" placeholder="Part Name" data-toggle="tooltip" data-placement="top" title="Free form"></td>
											<td width="5%"><input class="btn" type="button"  data-toggle="tooltip" data-placement="top" title="Add files for quotes or links to specific sites." value="Add Item"></td>
											<td width="5%"><input class="form-control" type="text" placeholder="#" data-toggle="tooltip" data-placement="top" title="Quantity"></td>
											<td width="5%"><input class="form-control" type="text" placeholder="#" data-toggle="tooltip" data-placement="top" title="TRU Price Per"></td>
											<td width="5%"><input class="btn btn-success btn-sm" type="button" name="addRow" value="+" data-toggle="tooltip" data-placement="top" title="Will add more rows, not currently enabled"></td>
										</tr>
									</table>
								</div>
							
								<input class="btn btn-primary btn-lg" type="Submit" name="saveHours" value="Save Estmiation" data-toggle="tooltip" data-placement="top" title="Save to Database and come back later">
								<input type="button" class="btn btn-secondary btn-lg" name="quote" value="Convert To Quote" data-toggle="tooltip" data-placement="top" title="Save to Database and start work order">
							</form>
						</div>
					</div>
					<!-- <div class="row" id="rightColumn">
						<div class="col-sm-2">
							<?php //include("../includes/layouts/TaskPane.php"); ?> Right side Menu
						</div>
					</div> -->
				</div>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<?php include("footer.php"); ?>